### ISSUE TITLE
Problème lancement des tests et revue de code

### ISSUE THREAD

**Issue by clement-cottet** [PolytechLyon/isi3-tp1-graph-chaput-cottet#1]
Bonjour,
Nous n'arrivons pas à lancer les tests via intellij qui nous renvoie une erreur "Erreur : impossible de trouver ou charger la classe principale TestGraph", avez-vous déjà rencontré le problème ?
Nous avons également implémenté une solution pour les questions 3 et 4, qu'en pensez-vous ?

**Comment by Slashgear** [comment]
Alors, essaye de compiler ton code. Sinon à distance j'aurai du mal à pouvoir t'aider plus.

Tu peux essayer de déplacer cette class de test dans le package main.

Pour l'implem des iterateur, c'est très bien mais je ferais la review quand le rapport sera terminé.

**Comment by clement-cottet** [comment]
On a réussi à résoudre le problème des tests, merci.
