### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by clement-cottet** [PolytechLyon/isi3-tp1-graph-chaput-cottet#2]
Pouvez-vous nous donner votre avis sur le code et le rapport ?
Merci par avance.

**Comment by Slashgear** [comment]
- 👍 Rapport très clean.
- [ ] ❓ Pourquoi une initialisation à null https://github.com/PolytechLyon/isi3-tp1-graph-chaput-cottet/blob/2aeee7ac6561c9f4c58e87d9ac76bae8ce0079ae/src/main/java/graph/GraphIterator.java#L11-L14
- [ ] la méthode `hashcode`de `Node`n'est pas implémenter, quels sont les impacts ?
- [ ] Ici le type pourrait être IGraph, pourquoi ? Est ce que ce serait mieux ? https://github.com/PolytechLyon/isi3-tp1-graph-chaput-cottet/blob/2aeee7ac6561c9f4c58e87d9ac76bae8ce0079ae/src/main/java/graph/UndirectedGraph.java#L9

**Comment by chaputan** [comment]
- L'initialisation à `null` permet d'indiquer explicitement que les attributs n'ont pas de référence au départ, mais ne sont pas forcément nécessaire en effet. Cela nous permettait d'avoir une sensation d'un meilleur contrôle du code.
- Nous utilisons `Set` et `HashSet` pour les itérateurs et se servent notamment de `HashCode()` pour garantir l'unicité. Ne pas l'implémenter diminuerait la performance de ces deux objets pour respecter la contrainte car il est plus facile et rapide de vérifier un *hash code* que de comparer les attributs un à un pour vérifier si deux nœuds sont uniques.
- On pourrait en effet utiliser `IGraph` car `IDirectedGraph` se sert de cette interface mais poserait problème lors de l'implémentation des méthodes concernant les arcs dans `UndirectedGraph` car n'existant pas dans l'objet servant pour la délégation si changement du type. Il faudrait dans ce cas *caster*, ce qui pourrait poser des problèmes inattendus et une lecture moins claire.
![ex_igraph](https://user-images.githubusercontent.com/26272908/37092234-4f71cbd4-220b-11e8-8047-d87f4b4cd397.png)

**Comment by Slashgear** [comment]
De base les attribut sont null donc faire = null c'est inutile 😉 
Sinon ok c'est terminé
